extends: standard
plugins:
  - import
env:
  browser: true
  node: true
  es6: true
rules: 
  max-len: [1, 80, 2]
  no-console: ["warn"]
  no-alert: ["warn"]
parserOptions:
  ecmaVersion: 2017
  sourceType: "module"